version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3
  continuation: circleci/continuation@0.1.2
  docker: circleci/docker@2.1.3

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/continue-config.yml
          mapping: |
            backend/* check-backend true
            frontend/* check-frontend true
