version: 2.1

orbs:
  docker: circleci/docker@2.1.3
  node: circleci/node@5.0.2

paramters:
  check-backend:
    type: boolean
    default: false
  check-frontend:
    type: boolean
    default: false

jobs:
  lint-docker:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "18.8"
      - run: node --version
      - run:
          name: run formatter
          command: |
            npx prettier@2 --check "**/*.{md,yaml,yml,json}"

  lint-backend:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: lint backend
          command: black .

  lint-frontend:
    docker:
      - image: cimg/node:18
    steps:
      - checkout

workflows:
  common-workflow:
    jobs: lint-docker

  backend-workflow:
    when:
      or:
        - << pipeline.parameters.check-backend >>
    jobs:
      - lint-backend:
          requires:
            - lint-docker

  frontend-workflow:
    when:
      or:
        - << pipeline.parameters.check-frontend >>
