FROM python:3.9-bullseye AS install_pipenv

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir pipenv

CMD ["bash"]

FROM install_pipenv AS virtual_env

ENV VENV_DIR /root/venv
ENV VENV_NAME bv
ENV VENV ${VENV_DIR}/${VENV_NAME}

RUN python3 -m venv ${VENV}
RUN chmod u+x ${VENV}/bin/activate

FROM virtual_env AS poetry_install

WORKDIR /root/backend-app
COPY pyproject.toml poetry.lock ./ 
RUN . ${VENV}/bin/activate && pipenv sync
